export const hotessesAssessmentQuestions = [
  {
    id: "hotesses-1",
    prompt: "Quelle différence décrit correctement les deux rôles présentés ?",
    options: [
      "L’hôtesse d’accueil reçoit et oriente à un événement ; l’hôtesse de proximité va vers les clients d’un lieu fixe avec tact et permission.",
      "L’hôtesse d’accueil prospecte uniquement ; l’hôtesse de proximité gère les invitations officielles.",
      "Les deux rôles consistent à attendre que les clients demandent de l’aide.",
      "L’hôtesse de proximité est uniquement chargée du contrôle des accès.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-2",
    prompt: "Avant d’aborder une personne dans un café, un shop ou un aéroport, quel réflexe est le plus juste ?",
    options: [
      "Observer le contexte, choisir un moment disponible, demander brièvement l’autorisation d’échanger et respecter la réponse.",
      "Interrompre immédiatement une conversation pour présenter le service.",
      "Se placer très près de la personne afin d’obtenir son attention.",
      "Insister jusqu’à ce que la personne accepte de répondre.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-3",
    prompt: "La préparation P.R.Ê.T.E. sert d’abord à :",
    options: [
      "Vérifier plan, référent, état de préparation, terrain et escalade avant la première interaction.",
      "Mémoriser un discours commercial long et identique pour chaque lieu.",
      "Évaluer l’apparence et le sourire des membres de l’équipe.",
      "Remplacer le brief de site et les contacts locaux.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-4",
    prompt: "Quelle présence professionnelle soutient le mieux le service ?",
    options: [
      "Une tenue propre et fonctionnelle, une posture mobile, un passage libre, une voix adaptée et une expression disponible, calme ou neutre selon la situation.",
      "Un sourire permanent, même en cas de tension ou d’inconfort.",
      "Une tenue choisie uniquement pour attirer l’attention des clients.",
      "Une immobilité stricte, sans pause ni changement de position.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-5",
    prompt: "Lorsqu’un invité paraît perdu à un événement, la bonne première réponse est :",
    options: [
      "L’accueillir, se situer, clarifier sa destination, vérifier ce que le brief autorise puis donner une suite précise.",
      "Lui dire de chercher un panneau sans poser de question.",
      "Le renvoyer vers un autre espace sans vérifier son besoin.",
      "Lui demander d’attendre sans lui expliquer la suite.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-6",
    prompt: "L’empathie professionnelle consiste surtout à :",
    options: [
      "Reconnaître le besoin ou l’émotion, vérifier les faits et proposer une aide réaliste ou un relais dans son périmètre.",
      "Être d’accord avec toutes les demandes, même impossibles.",
      "Éviter les personnes qui semblent contrariées.",
      "Partager une expérience privée pour prouver que l’on comprend.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-7",
    prompt: "Dans ce module, « créer l’envie » ou « séduire professionnellement » signifie :",
    options: [
      "Créer un contact respectueux par une présentation utile, une énergie maîtrisée et une réponse adaptée au besoin.",
      "Utiliser une approche personnelle ou romantique pour obtenir une adhésion.",
      "Insister sur la personne jusqu’à obtenir une réponse positive.",
      "Cacher les limites du service pour rendre l’offre plus attractive.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-8",
    prompt: "Dans la méthode PAUSE, quelle réponse est juste face à une tension ou une préoccupation personnelle ?",
    options: [
      "Percevoir son état, ancrer le corps, utiliser une phrase neutre, solliciter un relais puis escalader si nécessaire.",
      "Cacher son état, sourire quoi qu’il arrive et finir seule l’échange.",
      "Raconter son problème personnel au client pour expliquer son attitude.",
      "Quitter immédiatement le poste sans prévenir personne.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-9",
    prompt: "Dans un lieu HORECA, quel comportement de prospection respecte le mieux le client et le lieu ?",
    options: [
      "Choisir un moment propice, rester brève, proposer de revenir plus tard si la personne est occupée et ne pas gêner le service.",
      "Aborder chaque table dès l’arrivée des clients, quel que soit le contexte.",
      "Bloquer le passage afin d’obtenir l’attention des personnes.",
      "Multiplier les relances après un refus clair.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-10",
    prompt: "Quelle donnée ne doit jamais être demandée, regardée, notée ou transmise pendant une assistance M-Pesa ?",
    options: [
      "Le PIN, un OTP/code à usage unique, un mot de passe ou un écran de transaction non nécessaire.",
      "Le nom public d’un service présenté sur un support officiel.",
      "L’emplacement général du stand d’accueil.",
      "L’heure de début de la campagne communiquée par le brief.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-11",
    prompt: "Après un échange utile qui n’aboutit pas immédiatement, la bonne conclusion est :",
    options: [
      "Résumer la prochaine étape réaliste, remercier, puis consigner ou remonter l’information selon le brief.",
      "Demander au client de décider tout de suite, même s’il hésite.",
      "Conserver ses données personnelles au cas où elles serviraient plus tard.",
      "Promettre une réduction ou un avantage non confirmé.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-12",
    prompt: "Quelle situation impose de solliciter rapidement le responsable, la sécurité ou les secours selon le brief ?",
    options: [
      "Un danger, une menace, un contact non consenti, un passage bloqué, une alarme ou un malaise.",
      "Toute question simple à laquelle la fiche de briefing répond clairement.",
      "Un client qui remercie après une orientation réussie.",
      "Un échange de routine terminé normalement.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-13",
    prompt: "Une personne demande le numéro personnel ou le réseau social de l’hôtesse pendant la mission. Quelle réponse respecte le cadre ?",
    options: [
      "Rediriger ou clore : « Je préfère garder cela privé. Pour le service, je peux vous orienter vers le canal officiel. »",
      "Donner une coordonnée privée pour ne pas décevoir la personne.",
      "Accepter un rendez-vous après le service pour conserver le client.",
      "Demander au client de justifier sa question avant de poursuivre.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-14",
    prompt: "Après une limite posée, une personne insiste et se rapproche. Quel réflexe L.I.E.R. est adapté ?",
    options: [
      "Mettre fin à l’échange, garder distance et issue, rejoindre une zone visible ou l’équipe, alerter puis rapporter les faits quand la sécurité est assurée.",
      "Rester seule et négocier longtemps pour prouver son professionnalisme.",
      "Répondre par une provocation pour imposer le respect.",
      "Bloquer physiquement la personne pour l’empêcher de partir.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-15",
    prompt: "Quelle affirmation respecte le mieux la frontière entre vie personnelle et service ?",
    options: [
      "Une émotion ou une difficulté personnelle peut conduire à demander une pause ou une relève ; elle ne doit pas être déversée sur le client ni portée seule.",
      "Une hôtesse doit cacher toute émotion et ne jamais demander de soutien.",
      "Le client doit écouter les détails personnels afin de mieux comprendre le service.",
      "La pause prévue peut être supprimée si le poste est chargé.",
    ],
    answer: 0,
  },
  {
    id: "hotesses-16",
    prompt: "Quel reporting F.A.I.T.S. est le plus utile après un incident ?",
    options: [
      "Faits ou paroles observés, action prise, interlocuteur alerté, temps et lieu approximatifs, suite attendue — sans jugement ni détail intime inutile.",
      "Une opinion sur la personnalité de la personne et des détails privés de l’hôtesse.",
      "Une capture d’écran du téléphone du client partagée dans le groupe équipe.",
      "Aucun signalement, pour éviter d’alourdir la mission.",
    ],
    answer: 0,
  },
];
